from django.db import models
from user.models import User
from company.models import MainCompany
class Group(models.Model):
    company = models.ForeignKey(MainCompany, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)

class Permission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    access = models.BooleanField(default=False)
    add_list_item = models.BooleanField(default=False)
    update_list = models.BooleanField(default=False)
    delete_list = models.BooleanField(default=False)
    delete_item = models.BooleanField(default=False)
    update_item = models.BooleanField(default=False)
    add_owner_of_goods = models.BooleanField(default=False)
    delete_owner_of_goods = models.BooleanField(default=False)
    update_owner_of_goods = models.BooleanField(default=False)
    add_rout = models.BooleanField(default=False)
    update_rout = models.BooleanField(default=False)
    delete_rout = models.BooleanField(default=False)
    add_station = models.BooleanField(default=False)
    update_station = models.BooleanField(default=False)
    delete_station = models.BooleanField(default=False)
    add_truck = models.BooleanField(default=False)
    update_truck = models.BooleanField(default=False)
    delete_truck = models.BooleanField(default=False)
    add_driver= models.BooleanField(default=False)
    update_driver= models.BooleanField(default=False)
    delete_driver= models.BooleanField(default=False)
    add_company = models.BooleanField(default=False)
    update_company = models.BooleanField(default=False)
    delete_company = models.BooleanField(default=False)
    add_demurrage = models.BooleanField(default=False)
    update_demurrage = models.BooleanField(default=False)
    delete_demurrage = models.BooleanField(default=False)
    add_warehousing = models.BooleanField(default=False)
    update_warehousing = models.BooleanField(default=False)
    delete_warehousing = models.BooleanField(default=False)
    users = models.BooleanField(default=False)
    add_bill = models.BooleanField(default=False)
    update_bill = models.BooleanField(default=False)
    disable_bill = models.BooleanField(default=False)
    add_continer = models.BooleanField(default=False)
    update_continer = models.BooleanField(default=False)
    delete_continer = models.BooleanField(default=False)
    manage_attachments = models.BooleanField(default=False)
    container_demurrage_management = models.BooleanField(default=False)
    booking_management = models.BooleanField(default=False)
    truck_exit = models.BooleanField(default=False)
    management_of_loading_costs = models.BooleanField(default=False)
    Upload_the_documents_attached_to_the_bill_of_lading = models.BooleanField(default=False) #آپلود مدارک ضمیمه بارنامه
    list_of_issued_bills_of_lading = models.BooleanField(default=False) #لیست بارنامه های صادر شده   

